package com.example.ddsigrupo33serverside.Enums;

public enum Permiso {
  ACCEDER_PANEL,
  CREAR_COLECCION,
  EDITAR_COLECCION,
  ELIMINAR_COLECCION,
  CONFIGURAR_FUENTES,
  CONFIGURAR_ALGORITMO_CONSENSO,
  APROBAR_MODIFICACION_HECHO,
  RECHAZAR_MODIFICACION_HECHO,
  ACEPTAR_MODIFICACION_HECHO,
  APROBAR_SOLICITUD_ELIMINACION_HECHO,
  RECHAZAR_SOLICITUD_ELIMINACION_HECHO,
  IMPORTAR_HECHOS
}
