spring.application.name=ddsi-grupo-33-server-side
server.port=8081

spring.servlet.multipart.max-file-size=55MB
spring.servlet.multipart.max-request-size=55MB

server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB

BACKEND_URL=http://localhost:8080